# Wire up travis
language: python

python:
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - 3.5
  - pypy3

install: python setup.py -q dev

script: python setup.py -q test -q

notifications:
  email:
    - pyramid-checkins@lists.repoze.org
